### ISSUE TITLE
Scripts are creashing on execution

### ISSUE THREAD

**Issue by becknik** [coolmule0/JLPT-N5-N1-Japanese-Vocabulary-Anki#6]
Hello,

I tried to run your scripts, but somehow all of them seem to crash:

```bash
2023-09-27 22:20:32,172 INFO ---------- Converting jlpt-n5
Traceback (most recent call last):
  File "/home/jnnk/build/git/JLPT-N5-N1-Japanese-Vocabulary-Anki/createJLPTDeck.py", line 459, in <module>
    download_and_generate(N, args.type)
  File "/home/jnnk/build/git/JLPT-N5-N1-Japanese-Vocabulary-Anki/createJLPTDeck.py", line 415, in download_and_generate
    pddata = pd.read_json(json_file, orient="split", encoding="utf-8")
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 804, in read_json
    return json_reader.read()
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1014, in read
    obj = self._get_object_parser(self.data)
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1040, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1173, in parse
    self._parse()
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1376, in _parse
    for col in decoded["columns"]
KeyError: 'columns'
```

## Here is what I did:

1. Create a pyenf

```bash
$ pipenv shell                               
Warning: Python 3.9 was not found on your system...
Would you like us to install CPython 3.9.18 with Pyenv? [Y/n]: y
Installing CPython 3.9.18 with /usr/bin/pyenv (this may take a few minutes)...
✔ Success!
⠙ Installing python...
Creating a virtualenv for this project...
Pipfile: /home/jnnk/build/git/JLPT-N5-N1-Japanese-Vocabulary-Anki/Pipfile
Using /home/jnnk/.pyenv/versions/3.9.18/bin/python3.9 (3.9.18) to create virtualenv...
⠙ Creating virtual environment...created virtual environment CPython3.9.18.final.0-64 in 114ms
  creator CPython3Posix(dest=/home/jnnk/.local/share/virtualenvs/JLPT-N5-N1-Japanese-Vocabulary-Anki-CPLiNN8i, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jnnk/.local/share/virtualenv)
    added seed packages: pip==23.2.1, setuptools==68.2.0, wheel==0.41.2
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/jnnk/.local/share/virtualenvs/JLPT-N5-N1-Japanese-Vocabulary-Anki-CPLiNN8i
Launching subshell in virtual environment...
 . /home/jnnk/.local/share/virtualenvs/JLPT-N5-N1-Japanese-Vocabulary-Anki-CPLiNN8i/bin/activate
Found pyenv, but it is badly configured (missing pyenv shims in $PATH). pyenv might not
work correctly for non-interactive shells (for example, when run from a script).

To fix this message, add these lines to the '.profile' and '.zprofile' files
in your home directory:

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

You'll need to restart your user session for the changes to take effect.
For more information go to https://github.com/pyenv/pyenv/#installation.
```

2. Installed necessary dependencies:

```bash
$ pip install pandas
$ pip install bs4
```

3. Run `python createJLPTDeck.py -v --type extended`
What happens here:
```bash
2023-09-27 22:20:01,124 DEBUG Searching https://jisho.org/api/v1/search/words?keyword=%23jlpt-n5&page=1
2023-09-27 22:20:02,648 DEBUG Found 20 results
...
2023-09-27 22:20:31,434 DEBUG Found 17 results
2023-09-27 22:20:31,434 DEBUG Searching https://jisho.org/api/v1/search/words?keyword=%23jlpt-n5&page=34
2023-09-27 22:20:32,133 DEBUG Found 0 results
2023-09-27 22:20:32,133 INFO Found 33 pages 
2023-09-27 22:20:32,172 INFO ---------- Converting jlpt-n5
Traceback (most recent call last):
  File "/home/jnnk/build/git/JLPT-N5-N1-Japanese-Vocabulary-Anki/createJLPTDeck.py", line 459, in <module>
    download_and_generate(N, args.type)
  File "/home/jnnk/build/git/JLPT-N5-N1-Japanese-Vocabulary-Anki/createJLPTDeck.py", line 415, in download_and_generate
    pddata = pd.read_json(json_file, orient="split", encoding="utf-8")
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 804, in read_json
    return json_reader.read()
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1014, in read
    obj = self._get_object_parser(self.data)
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1040, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1173, in parse
    self._parse()
  File "/home/jnnk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1376, in _parse
    for col in decoded["columns"]
KeyError: 'columns'
```

**Comment by CatalinStefan** [comment]
I ran into this problem as well and found a workaround
It seems that there was a breaking change in pandas at some point.
You need to install a lower version

pip uninstall pandas
pip install pandas==1.3.1

**Comment by becknik** [comment]
Thanks for the response, the script now seems to run properly.

For future readers: I discovered the [requirements.txt](https://github.com/coolmule0/JLPT-N5-N1-Japanese-Vocabulary-Anki/blob/main/requirements.txt) file in this repository which states the exact versions the author used (`pandas==1.3.0` btw).
It might be beneficial to mention such a file in the README for confused people like me, but now at least it's existence is mentioned here ;)
